<script>
  import Container from "$lib/components/Container.svelte";
</script>

<Container>
<h1>Privacyverklaring</h1>
<p>Deze verklaring geldt voor Tricks for Bricks bvba, gevestigd aan de Korte Keppestraat 7/61 in 9320 Erembodegem en voor alle handelsnamen die gelieerd zijn aan of gebruikt worden door Tricks for Bricks bvba (Real Estate Classic Tour, Bricks to Invest, etc). Deze verklaring is bovendien niet alleen van toepassing op de website van Tricks for Bricks, maar eveneens op alle portaalsites die de onderneming beheert en algemeen op alle communicatie die Tricks for Bricks voert.</p>
<p>Om u en uw bedrijf optimaal van dienst te kunnen zijn, is het noodzakelijk dat Tricks for Bricks uw contactgegevens kan gebruiken en alle relevante informatie over u kan bijhouden en gebruiken. Daarbij willen we uiteraard uw privacy maximaal respecteren. We wensen dan ook helemaal in regel te zijn met de Europese privacywetgeving, (GDPR - General Data Protection Regulation) of AVG (Algemene Verordening Gegevensbescherming).</p>
<p>Vanuit die regelgeving verzamelt en gebruikt Tricks for Bricks bvba uw persoonsgegevens enkel om welbepaalde redenen. We beperken ons steeds tot wat echt nodig is.</p>
<p>In het kader van onze contractuele overeenkomsten houden we vanzelfsprekend contactgegevens bij om met prospecten, klanten, leveranciers en partners te communiceren. Deze gegevens gebruiken we ook om u verder te informeren over producten en diensten die in lijn liggen met de contacten die we al met u hebben.</p>
<p>Via het invulformulier op onze website, via directe of telefonische gesprekken of bij andere aanvragen om informatie geven we u de gelegenheid ons uw contactgegevens en uw interesses zelf te bezorgen. Mits uw expliciete goedkeuring zullen we deze gegevens daarna verder gebruiken om u onze nieuwsbrief toe te sturen of u andere informatie te bezorgen over onze producten en diensten.</p>
<p>Als u onze website raadpleegt, willen we graag weten naar welke van onze activiteiten uw interesse uitgaat. Het merendeel van deze gegevens verwerken we anoniem, maar als u een contactformulier invult of naar de website doorklikt vanaf een mail die we u toestuurden, linken we deze informatie aan uw persoon. Hierdoor kunnen we nader op uw behoeften ingaan en verbeteren we het gebruik en toegang van onze website of onze portaaltoepassingen. We maken daarbij ook gebruik van cookies en web beacons. We menen dat dit een gerechtvaardigd gebruik van deze informatie is, waarmee we geen inbreuk doen op uw recht op privacy. U kunt altijd via uw browserinstellingen het plaatsen van cookies uitsluiten, maar mogelijk zult u bepaalde functionaliteiten dan niet kunnen gebruiken. Als u meer wilt weten over cookies, wat ze precies doen en hoe u ze kunt verwijderen of weren, verwijzen we u graag door naar volgende website: <a href="http://www.aboutcookies.org">www.aboutcookies.org</a></p>
<p>Persoonsgegevens die u ons als klant toevertrouwt om er in uw opdracht een verwerking mee te doen, gebruiken we vanzelfsprekend enkel en alleen voor de door u duidelijk omschreven opdracht. Deze gegevens worden nooit voor een ander doel ingezet. Wij beschermen alle verzamelde persoonsgegevens als uiterst vertrouwelijke informatie.</p>
<p>Alle werknemers en partners van Tricks for Bricks bvba onderschrijven een vertrouwelijkheidsovereenkomst, waarin zij de verplichting op zich nemen de informatie waarmee ze in het kader van hun job in contact komen, steeds en blijvend als strikt vertrouwelijk te behandelen.</p>
<p>De nodige controlemechanismen, softwarematig en manueel, zijn aanwezig om de kwaliteit van de data te bewaken. Naargelang het type van informatie wordt een bewaartermijn vastgesteld, waarna de verzamelde gegevens volledig en definitief verwijderd worden. Persoonsgegevens worden zoveel mogelijk intern bewaard en verwerkt.</p>
<p>Zij worden enkel aan externe partijen doorgegeven in het kader van een beproefd partnerschap of binnen een contractueel goed omschreven opdracht, onder onze verantwoordelijkheid uitgevoerd. U hebt als betrokkene steeds het recht om op de hoogte te zijn van de gegevens die we over u verzamelen. U mag deze opvragen, corrigeren of helemaal laten wissen. Indien u meent dat Tricks for Bricks bvba onrechtmatig met uw persoonsgegevens omgaat of op enigerlei wijze de wetten en de regelgeving overtreedt, hebt u het recht een klacht in te dienen bij de Privacycommissie.</p>
<p>Vragen omtrent de verwerkingen die we doen met uw persoonsgegevens of verzoeken om deze gegevens te corrigeren, aan te vullen of te wissen, kunt u, vergezeld van een motivatie voor uw vraag, via een mail aan info@tricksforbricks.be of per post aan Tricks for Bricks bvba, Korte Keppestraat 7/61, in 9320 Erembodegem. Aan uw verzoek wordt binnen de vier weken voldaan, tenzij deze termijn door extra complicaties niet haalbaar zou zijn of tenzij er conflicten zouden optreden met de privacy van andere personen of het doorgeven van de informatie door de wet verboden zou zijn. In dergelijk geval wordt u eveneens steeds binnen de vier weken een verklaring gegeven.</p>
<p>Ook als u ons toestemming hebt gegeven uw gegevens te gebruiken, kunt u te allen tijde deze toestemming weer intrekken. Als we u met uw goedkeuring een nieuwsbrief toesturen, zal er ook altijd een gemakkelijk te gebruiken functie worden voorzien om u uit te schrijven.</p>
<p>Wij werken deze verklaring regelmatig bij zodat ze een correct beeld geeft van onze intenties en onze werkwijze, die steeds wordt aangepast aan de regelgeving. We suggereren dan ook dat u af en toe deze tekst herbekijkt als u onze website bezoekt of van onze online diensten gebruik maakt.</p>
<p>Met alle vragen omtrent persoonsgegevens kan u terecht bij onze zaakvoerder, die als primaire taak heeft uw rechten te verzekeren. U kunt deze bereiken op het volgende mailadres: <a href="mailto:jo@tricksforbricks.be">jo@tricksforbricks.be</a>.</p>
</Container>